const prefix = 'dmnstudio_'

export const ROLES = {
    READ: `${prefix}read`,
    DEPLOYER: `${prefix}deployer`,
    ADMIN: `${prefix}admin`,
    DEVELOPER: `${prefix}developer`,
    APPROVER: `${prefix}approver`
};

export const ROUTE_ROLES = {
    DEPLOYMENT_LIST: [ROLES.ADMIN, ROLES.DEPLOYER, ROLES.DEVELOPER],
    DEPLOYMENT_CREATE: [ROLES.ADMIN, ROLES.DEPLOYER],
    DEPLOYMENT_DETAIL: [ROLES.ADMIN, ROLES.DEPLOYER],
    TEST_LIST: [ROLES.ADMIN, ROLES.DEVELOPER, ROLES.APPROVER, ROLES.DEPLOYER],
    TEST_DETAIL: [ROLES.ADMIN, ROLES.DEVELOPER, ROLES.APPROVER, ROLES.DEPLOYER],
    TEST_CREATE: [ROLES.ADMIN, ROLES.DEVELOPER, ROLES.DEPLOYER],
    DMN_SUBMIT: [ROLES.ADMIN, ROLES.DEVELOPER, ROLES.DEPLOYER],
    DMN_EDIT: [ROLES.ADMIN, ROLES.DEVELOPER, ROLES.DEPLOYER],
    DMN_VIEW: [ROLES.ADMIN, ROLES.DEVELOPER, ROLES.APPROVER, ROLES.DEPLOYER, ROLES.READ],
    DMN_REVIEW: [ROLES.ADMIN, ROLES.DEVELOPER, ROLES.APPROVER, ROLES.DEPLOYER],
    DMN_VERSION_CREATE: [ROLES.ADMIN, ROLES.DEVELOPER, ROLES.DEPLOYER],
    DMN_DETAIL: [ROLES.ADMIN, ROLES.DEVELOPER, ROLES.APPROVER, ROLES.DEPLOYER, ROLES.READ],
    DMN_CREATE: [ROLES.ADMIN, ROLES.DEVELOPER, ROLES.DEPLOYER],
    DMN_LIST: [ROLES.ADMIN, ROLES.DEVELOPER, ROLES.APPROVER, ROLES.DEPLOYER, ROLES.READ],
    HOME: [ROLES.ADMIN, ROLES.DEVELOPER, ROLES.APPROVER, ROLES.DEPLOYER, ROLES.READ],
    DOMAINS_VIEW: [ROLES.ADMIN, ROLES.DEVELOPER, ROLES.APPROVER, ROLES.DEPLOYER, ROLES.READ],
    DOMAIN_CREATE: [ROLES.ADMIN]
};
