name: Release

on:
  workflow_dispatch:

jobs:
    release:
        runs-on: ubuntu-latest
        steps:

            -   name: Checkout
                uses: actions/checkout@v6.0.2
                with:
                    fetch-depth: 0
                    persist-credentials: false # <--- this

            -   name: Setup Node.js environment
                uses: actions/setup-node@v6.4.0
                with:
                    node-version: "lts/*"
            -   name: Install dependencies
                run: yarn global add semantic-release @semantic-release/changelog @semantic-release/git @semantic-release/github @semantic-release/exec @semantic-release/release-notes-generator @semantic-release/commit-analyzer conventional-changelog-conventionalcommits

            -   name: Semantic Release
                run: semantic-release
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                    GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
